# Generated by Django 4.1.3 on 2022-12-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(max_length=128, verbose_name='Name of mail')),
                ('login', models.CharField(max_length=128, verbose_name='Login')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=128, verbose_name='Telegram ID')),
                ('is_blocked_bot', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('telegram_id', 'is_blocked_bot')},
            },
        ),
        migrations.DeleteModel(
            name='MailAuth',
        ),
        migrations.AddField(
            model_name='mailbox',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', related_query_name='mailboxes', to='samples.user'),
        ),
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together={('user', 'mail_id', 'login', 'password')},
        ),
    ]
