# Generated by Django 4.1.3 on 2022-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_mailbox_user_delete_mailauth_mailbox_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='filter',
            field=models.CharField(default='UNSEEN', max_length=128, verbose_name='Filter'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='filter_translation',
            field=models.CharField(default='Непрочитанные письма', max_length=128, verbose_name='Filter translation'),
        ),
    ]
