# Generated by Django 4.1.3 on 2022-12-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_mailbox_unique_together_mailbox_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='is_active_search',
            field=models.BooleanField(default=False, verbose_name='Is Active Search'),
        ),
    ]
