# Generated by Django 4.1.3 on 2023-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_mailbox_is_active_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='oauth_token',
            field=models.CharField(max_length=128, null=True, verbose_name='OAuth Token'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='Password'),
        ),
    ]
