# Generated by Django 4.1.3 on 2022-12-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_alter_mailbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', related_query_name='mailbox', to='samples.user'),
        ),
    ]
