# Generated by Django 4.1.3 on 2023-02-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_mailbox_oauth_token_alter_mailbox_password'),
        ('samples', '0006_alter_mailbox_user'),
    ]

    operations = [
    ]
