# Generated by Django 4.1.3 on 2022-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=128, verbose_name='ID в телеграмм')),
                ('mail_id', models.CharField(max_length=128, verbose_name='Название почты')),
                ('mail_login', models.CharField(max_length=128, verbose_name='Логин в почте')),
                ('mail_password', models.CharField(max_length=128, verbose_name='Пароль от почты')),
            ],
            options={
                'unique_together': {('telegram_id', 'mail_id', 'mail_login')},
            },
        ),
    ]
